export const RANGE_SLIDER_DEFAULTS = {
    min: 0,
    max: 100,
    step: 1,
    disabled: false,
    ariaLabel: 'Selector de rango',
    className: '',
    unstyled: false as const,
} as const;

export const RANGE_SLIDER_CLASSES = {
    wrapper: 'w3f-range-slider-wrapper',
    isDisabled: 'is-disabled',
    hasError: 'has-error',
    track: 'w3f-range-track',
    active: 'w3f-range-active',
    thumb: 'w3f-range-thumb-custom',
    thumbDragging: 'is-dragging',
    thumbCloseMin: 'is-close-min',
    thumbCloseMax: 'is-close-max',
    clickable: 'w3f-range-clickable-area',
    labelMin: 'w3f-range-label w3f-range-label-min',
    labelMax: 'w3f-range-label w3f-range-label-max',
    labelVisible: 'w3f-range-label-visible',
    labelClose: 'is-close',
    labelArrow: 'w3f-range-label-arrow',
    inputA11y: 'w3f-range-input-a11y',
    inputMin: 'w3f-range-input-min',
    inputMax: 'w3f-range-input-max',
    valueLabelWrapper: 'w3f-value-label-wrapper',
    valueLabelGroup: 'w3f-value-label-group',
    valueLabelText: 'w3f-value-label-text',
    valueLabelValue: 'w3f-value-label-value',
    srOnly: 'w3f-sr-only',
    error: 'w3f-mt-2 w3f-text-sm w3f-text-error',
} as const;
