/**
 * Curated icon registry — imports ONLY the icons actually used in the project.
 * This avoids `import * as LucideIcons from 'lucide-react'` which pulls ~565 KB.
 *
 * To add a new icon: import it from 'lucide-react' and add it to the ICON_REGISTRY map.
 */
import type { LucideIcon } from 'lucide-react';

// ── Navigation ──
import {
    Home,
    Menu,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsDownUp,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ArrowUpDown,
    ExternalLink,
    Navigation,
} from 'lucide-react';

// ── Actions / General ──
import {
    Heart,
    Star,
    Bookmark,
    Share,
    Share2,
    Download,
    Upload,
    Copy,
    Edit,
    Trash,
    Trash2,
    Plus,
    PlusCircle,
    Send,
    Save,
    Printer,
    RotateCcw,
    Paintbrush,
    Pencil,
    PencilRuler,
    Rocket,
    Maximize2,
    Scissors,
    Shuffle,
    Newspaper,
    ClipboardList,
    LogIn,
} from 'lucide-react';

// ── Communication ──
import {
    Mail,
    MessageSquare,
    MessageCircle,
    Phone,
    Video,
    Bell,
} from 'lucide-react';

// ── Media ──
import {
    Play,
    Pause,
    Volume2 as Volume,
    VolumeX,
    Music,
    Image,
    Film,
    Camera,
} from 'lucide-react';

// ── Files / Documents ──
import {
    File,
    FileText,
    Folder,
    FolderOpen,
} from 'lucide-react';

// ── Status ──
import {
    Check,
    X,
    AlertCircle,
    AlertTriangle,
    Info,
    CheckCircle,
    XCircle,
    HelpCircle,
    Shield,
    Flame,
    Zap,
    Lightbulb,
} from 'lucide-react';

// ── Social ──
import {
    Facebook,
    Twitter,
    Instagram,
    Linkedin,
    Github,
    Youtube,
} from 'lucide-react';

// ── UI / Layout ──
import {
    Settings,
    Settings2,
    Search,
    Filter,
    Grid3x3,
    List,
    MoreVertical,
    MoreHorizontal,
    Loader2,
    Sliders,
    SlidersHorizontal,
    Layers,
    SquareStack,
    Archive,
    Palette,
    Rainbow,
    Code,
    Ruler,
    Type,
    Calendar,
    Clock,
    Monitor,
    MoveHorizontal,
    Smartphone,
    Tablet,
    Sun,
    Moon,
    Globe,
    DollarSign,
    CreditCard,
    Lock,
    Key,
    Eye,
    EyeOff,
    MapPin,
} from 'lucide-react';

// ── User ──
import {
    User,
    UserCircle,
    Users,
    UserPlus,
    UserMinus,
    UserCheck,
} from 'lucide-react';

// ── Formatting ──
import {
    Bold,
    Italic,
    Underline,
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignJustify,
    ZoomIn,
    ZoomOut,
} from 'lucide-react';

// ── Shapes / Surfaces ──
import {
    Circle,
    Square,
    Minus,
    Slash,
    Box,
    Boxes,
    Sidebar,
    Tag,
    CircleDot,
    ToggleLeft,
    ToggleRight,
    CheckSquare,
    GitBranch,
    GitCommitHorizontal,
    Package,
    Truck,
    BookOpen,
    Quote,
    Smile,
    Frown,
    Meh,
    Ban,
    Crosshair,
    Link2,
} from 'lucide-react';

// ── Layout panels ──
import {
    PanelLeft,
    PanelLeftOpen,
    PanelRight,
    PanelTop,
    PanelBottom,
    Layout,
    LayoutGrid,
    LayoutTemplate,
    LayoutPanelLeft,
    Columns3,
    Rows3,
    AppWindow,
    MousePointer,
    MousePointerClick,
} from 'lucide-react';

// ── Shopping ──
import {
    ShoppingCart,
} from 'lucide-react';

// ── Studio / TC ──
import {
    Sparkles,
    FileInput,
    FormInput,
    LayoutDashboard,
    HardDrive,
    HardDriveDownload,
    HardDriveUpload,
    FileCode,
    Redo2,
    Undo2,
    RefreshCw,
    AlertOctagon,
    RectangleHorizontal,
    Award,
    TextCursorInput,
    Hash,
    Wand2,
    Scan,
    ScanSearch,
    ClipboardPaste,
    ArrowLeftRight,
    ChevronsUpDown,
    ListOrdered,
    Loader,
    PaintBucket,
    Table2,
    Table as TableIcon,
    Link as LinkIcon,
    PlugZap,
    Unplug,
    Workflow,
    GitMerge,
    GitFork,
    PenLine,
    Timer,
    Radio,
    Wifi,
    Variable,
    Database,
    Server,
    FilePlus,
    Repeat,
    Scale,
    FileJson,
    Calculator,
    Group,
    Clapperboard,
    Map,
    BarChart3,
} from 'lucide-react';

// ── Alignment ──
import {
    AlignHorizontalJustifyStart,
    AlignHorizontalJustifyCenter,
    AlignHorizontalJustifyEnd,
    AlignHorizontalSpaceBetween,
    AlignVerticalJustifyStart,
    AlignVerticalJustifyCenter,
    AlignVerticalJustifyEnd,
    AlignVerticalSpaceBetween,
} from 'lucide-react';

/**
 * The curated map: PascalCase name → LucideIcon component.
 * Every icon used anywhere in the project must be listed here.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
    // Navigation
    Home,
    Menu,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsDownUp,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ArrowUpDown,
    ExternalLink,
    Navigation,

    // Actions
    Heart,
    Star,
    Bookmark,
    Share,
    Share2,
    Download,
    Upload,
    Copy,
    Edit,
    Trash,
    Trash2,
    Plus,
    PlusCircle,
    Send,
    Save,
    Printer,
    RotateCcw,
    Paintbrush,
    Pencil,
    PencilRuler,
    Rocket,
    Maximize2,
    Scissors,
    Shuffle,
    Newspaper,
    ClipboardList,
    LogIn,

    // Communication
    Mail,
    MessageSquare,
    MessageCircle,
    Phone,
    Video,
    Bell,

    // Media
    Play,
    Pause,
    Volume,
    VolumeX,
    Music,
    Image,
    Film,
    Camera,

    // Files
    File,
    FileText,
    Folder,
    FolderOpen,

    // Status
    Check,
    X,
    AlertCircle,
    AlertTriangle,
    Info,
    CheckCircle,
    XCircle,
    HelpCircle,
    Shield,
    Flame,
    Zap,
    Lightbulb,

    // Social
    Facebook,
    Twitter,
    Instagram,
    Linkedin,
    Github,
    Youtube,

    // UI / Layout
    Settings,
    Settings2,
    Search,
    Filter,
    Grid3x3,
    List,
    MoreVertical,
    MoreHorizontal,
    Loader2,
    Sliders,
    SlidersHorizontal,
    Layers,
    SquareStack,
    Archive,
    Palette,
    Rainbow,
    Code,
    Ruler,
    Type,
    Calendar,
    Clock,
    Monitor,
    MoveHorizontal,
    Smartphone,
    Tablet,
    Sun,
    Moon,
    Globe,
    DollarSign,
    CreditCard,
    Lock,
    Key,
    Eye,
    EyeOff,
    MapPin,

    // User
    User,
    UserCircle,
    Users,
    UserPlus,
    UserMinus,
    UserCheck,

    // Formatting
    Bold,
    Italic,
    Underline,
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignJustify,
    ZoomIn,
    ZoomOut,

    // Shapes / Surfaces
    Circle,
    Square,
    Minus,
    Slash,
    Box,
    Boxes,
    Sidebar,
    Tag,
    CircleDot,
    ToggleLeft,
    ToggleRight,
    CheckSquare,
    GitBranch,
    GitCommitHorizontal,
    Package,
    Truck,
    BookOpen,
    Quote,
    Smile,
    Frown,
    Meh,
    Ban,
    Crosshair,
    Link2,

    // Layout panels
    PanelLeft,
    PanelLeftOpen,
    PanelRight,
    PanelTop,
    PanelBottom,
    Layout,
    LayoutGrid,
    LayoutTemplate,
    LayoutPanelLeft,
    Columns3,
    Rows3,
    AppWindow,
    MousePointer,
    MousePointerClick,

    // Shopping
    ShoppingCart,

    // Studio / TC
    Sparkles,
    FileInput,
    FormInput,
    LayoutDashboard,
    HardDrive,
    HardDriveDownload,
    HardDriveUpload,
    FileCode,
    Redo2,
    Undo2,
    RefreshCw,
    AlertOctagon,
    RectangleHorizontal,
    Award,
    TextCursorInput,
    Hash,
    Wand2,
    Scan,
    ScanSearch,
    ClipboardPaste,
    ArrowLeftRight,
    ChevronsUpDown,
    ListOrdered,
    Loader,
    PaintBucket,
    Table2,
    Table: TableIcon,
    Link: LinkIcon,
    PlugZap,
    Unplug,
    Workflow,
    GitMerge,
    GitFork,
    PenLine,
    Timer,
    Radio,
    Wifi,
    Variable,
    Database,
    Server,
    FilePlus,
    Repeat,
    Scale,
    FileJson,
    Calculator,
    Group,
    // Studio sidebar icons
    Clapperboard,
    Map,
    BarChart3,
    // Alignment
    AlignHorizontalJustifyStart,
    AlignHorizontalJustifyCenter,
    AlignHorizontalJustifyEnd,
    AlignHorizontalSpaceBetween,
    AlignVerticalJustifyStart,
    AlignVerticalJustifyCenter,
    AlignVerticalJustifyEnd,
    AlignVerticalSpaceBetween,
};
